name: 'Setup Base Environment'
description: 'Sets up the Base environment'
inputs:
  windows:
    description: 'Whether to include Windows-specific setup'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: microsoft/setup-msbuild@v1.0.2
      name: Set up MSBuild
      if: ${{ inputs.windows == 'true' }}

    - name: Fetch submodules
      run: git submodule update --init --recursive
      shell: bash

    - uses: actions/setup-java@v4
      name: Set up JDK 22
      with:
        java-version: '22'
        distribution: 'temurin'

    - uses: gradle/actions/setup-gradle@v4
      name: Setup Gradle
