name: setup-linux.yaml
on:
  workflow_call:

jobs:
  setup-linux:
    runs-on: ${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Fetch submodules
        run: |
          git submodule update --init --recursive

      - uses: actions/setup-java@v4
        name: Set up JDK 22
        with:
          java-version: '22'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle
