name: 'Run Android Tests'
description: 'Runs Android tests using an emulator'
runs:
  using: "composite"
  steps:
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    # should be failed, but can generate the header to include in the project
    - name: Generate Native Header For NDK
      run: ./gradlew externalNativeBuildDebug
      continue-on-error: true
      shell: bash

    - name: Test it
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34
        arch: x86_64
        script: ./gradlew connectedAndroidTest
