name: release.yaml
on:
  workflow_dispatch:
    inputs:
      LIB_CORE_VERSION:
        description: 'Core library version'
        required: false
        default: ''
        type: string
      LIB_CORE_JAVA_VERSION:
        description: 'Core Java library version'
        required: false
        default: ''
        type: string
      LIB_PLATFORM_JVM_WINDOWS_VERSION:
        description: 'JVM Windows platform version'
        required: false
        default: ''
        type: string
      LIB_PLATFORM_JVM_LINUX_VERSION:
        description: 'JVM Linux platform version'
        required: false
        default: ''
        type: string
      LIB_PLATFORM_JVM_MACOS_VERSION:
        description: 'JVM macOS platform version'
        required: false
        default: ''
        type: string
      LIB_PLATFORM_ANDROID_VERSION:
        description: 'Android platform version'
        required: false
        default: ''
        type: string
      LIB_PLATFORM_IOS_VERSION:
        description: 'iOS platform version'
        required: false
        default: ''
        type: string

jobs:
  test-jvm-windows:
    if: ${{ inputs.LIB_PLATFORM_JVM_WINDOWS_VERSION != '' || inputs.LIB_CORE_JAVA_VERSION!= '' || inputs.LIB_CORE_VERSION!= '' }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base
        with:
          windows: 'true'

      - name: Run Test
        uses: ./.github/actions/test-jvm

  test-jvm-linux:
    if: ${{ inputs.LIB_PLATFORM_JVM_LINUX_VERSION != '' || inputs.LIB_CORE_JAVA_VERSION!= '' || inputs.LIB_CORE_VERSION!= '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-jvm

  test-jvm-macos:
    if: ${{ inputs.LIB_PLATFORM_JVM_MACOS_VERSION != '' || inputs.LIB_CORE_JAVA_VERSION!= '' || inputs.LIB_CORE_VERSION!= '' }}
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-jvm

  test-android:
    if: ${{ inputs.LIB_PLATFORM_ANDROID_VERSION != '' || inputs.LIB_CORE_JAVA_VERSION!= '' || inputs.LIB_CORE_VERSION!= '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-android

  test-ios:
    if: ${{ inputs.LIB_PLATFORM_IOS_VERSION != '' || inputs.LIB_CORE_JAVA_VERSION!= '' || inputs.LIB_CORE_VERSION!= '' }}
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-ios

  release-core:
    if: ${{ inputs.LIB_CORE_VERSION != '' }}
    needs:
      - test-jvm-windows
      - test-jvm-linux
      - test-jvm-macos
      - test-android
      - test-ios
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :core:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_CORE_VERSION: ${{ inputs.LIB_CORE_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-core-java:
    if: ${{ inputs.LIB_CORE_JAVA_VERSION != '' }}
    needs:
      - test-jvm-windows
      - test-jvm-linux
      - test-jvm-macos
      - test-android
      - test-ios
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :core-java:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_CORE_JAVA_VERSION: ${{ inputs.LIB_CORE_JAVA_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-jvm-windows:
    if: ${{ inputs.LIB_PLATFORM_JVM_WINDOWS_VERSION != '' }}
    needs:
      - test-jvm-windows
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base
        with:
          windows: 'true'

      - name: Publish
        run: ./gradlew :platform:platform-windows:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_PLATFORM_JVM_WINDOWS_VERSION: ${{ inputs.LIB_PLATFORM_JVM_WINDOWS_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-jvm-linux:
    if: ${{ inputs.LIB_PLATFORM_JVM_LINUX_VERSION != '' }}
    needs:
      - test-jvm-linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-linux:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_PLATFORM_JVM_LINUX_VERSION: ${{ inputs.LIB_PLATFORM_JVM_LINUX_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-jvm-macos:
    if: ${{ inputs.LIB_PLATFORM_JVM_MACOS_VERSION != '' }}
    needs:
      - test-jvm-macos
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-macos:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_PLATFORM_JVM_MACOS_VERSION: ${{ inputs.LIB_PLATFORM_JVM_MACOS_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-android:
    if: ${{ inputs.LIB_PLATFORM_ANDROID_VERSION != '' }}
    needs:
      - test-android
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-android:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_PLATFORM_ANDROID_VERSION: ${{ inputs.LIB_PLATFORM_ANDROID_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-ios:
    if: ${{ inputs.LIB_PLATFORM_IOS_VERSION != '' }}
    needs:
      - test-ios
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-ios:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          LIB_PLATFORM_IOS_VERSION: ${{ inputs.LIB_PLATFORM_IOS_VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
