name: release.yaml
on:
  workflow_dispatch:
    inputs:
      RELEASE_LIB_CORE:
        description: 'Release Core Library'
        required: false
        default: false
        type: boolean
      RELEASE_LIB_CORE_JAVA:
        description: 'Core Library Java Version'
        required: false
        default: false
        type: boolean
      RELEASE_LIB_PLATFORM_JVM_WINDOWS:
        description: 'Release JVM Windows Platform'
        required: false
        default: false
        type: boolean
      RELEASE_LIB_PLATFORM_JVM_LINUX:
        description: 'Release JVM Linux Platform'
        required: false
        default: false
        type: boolean
      RELEASE_LIB_PLATFORM_JVM_MACOS:
        description: 'Release JVM macOS Platform'
        required: false
        default: false
        type: boolean

      RELEASE_LIB_PLATFORM_ANDROID:
        description: 'Release Android Platform'
        required: false
        default: false
        type: boolean
      RELEASE_LIB_PLATFORM_IOS:
        description: 'Release iOS Platform'
        required: false
        default: false
        type: boolean
jobs:
  test-jvm-windows:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_JVM_WINDOWS || inputs.RELEASE_LIB_CORE || inputs.RELEASE_LIB_CORE_JAVA }}
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base
        with:
          windows: 'true'

      - name: Run Test
        uses: ./.github/actions/test-jvm

  test-jvm-linux:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_JVM_WINDOWS || inputs.RELEASE_LIB_CORE || inputs.RELEASE_LIB_CORE_JAVA }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-jvm

  test-jvm-macos:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_JVM_MACOS || inputs.RELEASE_LIB_CORE || inputs.RELEASE_LIB_CORE_JAVA }}
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-jvm

  test-android:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_ANDROID || inputs.RELEASE_LIB_CORE || inputs.RELEASE_LIB_CORE_JAVA }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-android

  test-ios:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_IOS || inputs.RELEASE_LIB_CORE || inputs.RELEASE_LIB_CORE_JAVA }}
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Run Test
        uses: ./.github/actions/test-ios

  release-core:
    if: ${{ inputs.RELEASE_LIB_CORE }}
    needs:
      - test-jvm-windows
      - test-jvm-linux
      - test-jvm-macos
      - test-android
      - test-ios
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :core:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-core-java:
    if: ${{ inputs.RELEASE_LIB_CORE_JAVA }}
    needs:
      - test-jvm-windows
      - test-jvm-linux
      - test-jvm-macos
      - test-android
      - test-ios
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :core-java:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-jvm-windows:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_JVM_WINDOWS }}
    needs:
      - test-jvm-windows
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base
        with:
          windows: 'true'

      - name: Publish
        run: ./gradlew :platform:platform-windows:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-jvm-linux:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_JVM_LINUX }}
    needs:
      - test-jvm-linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-linux:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-jvm-macos:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_JVM_MACOS }}
    needs:
      - test-jvm-macos
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-macos:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-android:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_ANDROID }}
    needs:
      - test-android
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-android:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

  release-platform-ios:
    if: ${{ inputs.RELEASE_LIB_PLATFORM_IOS }}
    needs:
      - test-ios
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-base

      - name: Publish
        run: ./gradlew :platform:platform-ios:publishAndReleaseToMavenCentral
        env:
          org.gradle.configuration-cache: false
          SKIP_SIGN: false
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRETKEYRING }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
