name: test
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
jobs:
  test-jvm-windows:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/setup-msbuild@v1.0.2
        name: Set up MSBuild

      - uses: actions/setup-java@v4
        name: Set up JDK 22
        with:
          java-version: '22'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Test it
        run: ./gradlew jvmTest

  test-jvm-liux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Set up JDK 22
        with:
          java-version: '22'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Test it
        run: ./gradlew jvmTest

  test-jvm-macos:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Set up JDK 22
        with:
          java-version: '22'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Test it
        run: ./gradlew jvmTest

  test-ios:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        name: Set up JDK 22
        with:
          java-version: '22'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Test it
        run: ./gradlew iosTest

  test-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Set up JDK 22
        with:
          java-version: '22'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
        name: Setup Gradle

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Test it
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew connectedAndroidTest
