name: test.yaml
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test-jvm-windows:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/meta/setup/setup-windows.yaml

      - name: Run Test
        uses: ./.github/workflows/meta/test/test-jvm.yaml

  test-jvm-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/meta/setup/setup-linux.yaml

      - name: Run Test
        uses: ./.github/workflows/meta/test/test-jvm.yaml

  test-jvm-macos:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/meta/setup/setup-macos.yaml

      - name: Run Test
        uses: ./.github/workflows/meta/test/test-jvm.yaml


  test-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/meta/setup/setup-linux.yaml

      - name: Run Test
        uses: ./.github/workflows/meta/test/test-android.yaml

  test-ios:
    runs-on: macos-15
    permissions:
      contents: read
    steps:
      - name: Setup Environment
        uses: ./.github/workflows/meta/setup/setup-macos.yaml

      - name: Run Test
        uses: ./.github/workflows/meta/test/test-ios.yaml
